version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: ember-cli
    versions:
    - ">= 0"
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: release-it
    versions:
    - 14.5.0
    - 14.5.1
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
    - 7.26.1
    - 7.26.2
    - 7.26.3
  - dependency-name: ember-auto-import
    versions:
    - 1.11.0
    - 1.11.2
  - dependency-name: ember-template-lint
    versions:
    - 3.1.1
    - 3.2.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.3.0
  - dependency-name: ember-source
    versions:
    - 3.25.3
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.6.4
    - 5.6.5
    - 5.7.0
